tidy and add helm

diff --git a/apps/x86_64-linux/install b/apps/x86_64-linux/install
--- a/apps/x86_64-linux/install
+++ b/apps/x86_64-linux/install
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -e
+set -exu
 
 check_installer() {
   if [ -e /etc/NIXOS ]; then
@@ -23,6 +23,11 @@ download_config() {
 
 run_apply() {
   ./bin/apply
+  if [ ! -f /tmp/username.txt ]; then
+    echo -e "\e[1;31mError: /tmp/username.txt does not exist.\e[0m"
+    exit 1
+  fi
+  export USERNAME=$(cat /tmp/username.txt)
 }
 
 run_disko() {
@@ -37,7 +42,22 @@ setup_files() {
 }
 
 install_nixos() {
-  sudo nixos-install --flake .#felix
+  ARCH=$(uname -m)
+
+  case "$ARCH" in
+    x86_64)
+      FLAKE_TARGET="x86_64-linux"
+      ;;
+    aarch64)
+      FLAKE_TARGET="aarch64-linux"
+      ;;
+    *)
+      echo -e "${RED}Unsupported architecture: $ARCH${CLEAR}"
+      exit 1
+      ;;
+  esac
+
+  sudo nixos-install --flake .#$FLAKE_TARGET $@
   sudo chmod -R 775 /mnt/etc/nixos
 }
 
@@ -49,11 +69,12 @@ prompt_reboot() {
   esac
 }
 
+cleanup
 check_installer
 download_config
+run_apply
 run_disko
 setup_files
-run_apply
 install_nixos
 cleanup
 prompt_reboot
